{
 "title": "MS SQL Query Analyzer",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "query_id",
    "query": "label_values(mssql_avg_duration_us,query_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Query",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mssql_avg_duration_us{query_id=~\"$query_id\"}"
    }
   ]
  },
  {
   "title": "Avg Duration",
   "type": "graph",
   "description": "Average duration for the query plan within the aggregation interval (reported in microseconds) .",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "mssql_avg_duration_us{query_id=~\"$query_id\"}",
     "legendFormat": "{{query_sql_text}}"
    }
   ]
  },
  {
   "title": "Count Execution",
   "type": "graph",
   "description": "Total count of executions for the query plan within the aggregation interval.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(mssql_total_execution_count{query_id=~\"$query_id\"}[1m])",
     "legendFormat": "{{query_sql_text}}"
    }
   ]
  },
  {
   "title": "Time Wait ms",
   "type": "graph",
   "description": "Total CPU wait time for the query plan within the aggregation interval and wait category (reported in milliseconds).",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(mssql_sum_total_wait_ms{query_id=~\"$query_id\"}[1m])",
     "legendFormat": "{{query_sql_text}}"
    }
   ]
  },
  {
   "title": "Row Count",
   "type": "graph",
   "description": "Average number of returned rows for the query plan within the aggregation interval.\nNote: Azure SQL Data Warehouse will always return zero (0).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(mssql_avg_rowcount{query_id=~\"$query_id\"}[1m])",
     "legendFormat": "{{query_sql_text}}"
    }
   ]
  },
  {
   "title": "IO Reads",
   "type": "graph",
   "description": "Average number of physical I/O reads for the query plan within the aggregation interval (expressed as a number of 8KB pages read).\nNote: Azure SQL Data Warehouse will always return zero (0).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mssql_avg_physical_io_reads{query_id=~\"$query_id\"}",
     "legendFormat": "{{query_sql_text}}"
    }
   ]
  }
 ]
}